### PR TITLE
fix: cert-manager duration expects XhYmZs format

### LINKED ISSUE #190: ArgoCD sync trying convert 87600h0m0s back to 87600h
Hello

Im using argocd to deploy pvc-autoresizer
In argocd sync the certificate get into the cluster with the duration parameter as 
`duration: 87600h0m0s`
Instead
`duration: 87600h`

What it means that the application in argo is always in a "not synced" state
Same goes to controller certificate

I guess to overcome it need to set minutes and seconds in the value in helm chart 

Image attached:

Screenshot from 2023-04-05 11-41-26

### PR DESCRIPTION
**Pull request by gozer**
It accepts shorter format like Yh, but the mutating webhook, if
installed/enabled will convert it to the full format, causing potential
endless reconciliation loops with tools like ArgoCD

Fixes #190

### CODE REVIEW

**Comment by llamerada-jp** [comment]
> if installed/enabled will convert it to the full format,  causing potential endless reconciliation loops with tools like ArgoCD

The reverse is also true, If there is a mutating webhook that converts to a shorter format, The change o this PR can cause endless reconcilation loop. I have checked and argocd works fine with both `87600h` and `87600h0m0s` descriptions. According to [upstream's comment](https://github.com/argoproj/argo-cd/issues/6008#issuecomment-1959963137), the problem was fixed at v2.10 or later.
I think you should first review the mutating webhook settings, and if you can't avoid the problem, change it so that it can handle both formats.

**Comment by gozer** [comment]
> The reverse is also true, If there is a mutating webhook that converts to a shorter format, The change to this PR can cause endless reconcilation loop. I have checked and argocd works fine with both `87600h` and `87600h0m0s` descriptions. 

The issue isn't with ArgoCD itself, but rather with cert-manager itself, it requires durations to be in that format, and it's cert-manager's own mutating webhook controller that makes this conversion transparently.

So, technically, a `Certificate` `spec.duration` field needs to be in this format to be _correct_, this this PR

**Comment by llamerada-jp** [comment]
Thanks for letting me know.

I tried to check the output format of cert-manager for the review, but I could not see the above behavior in my environment. It may be a difference in versions, so please tell me which version you tested. Or do I need any options for cert-manager?

**Comment by gozer** [comment]
> Thanks for letting me know.

No worries!

> I tried to check the output format of cert-manager for the review, but I could not see the above behavior in my environment. It may be a difference in versions, so please tell me which version you tested. Or do I need any options for cert-manager?

The validating/mutating webhook portion of cert-manager is an optional component.

I've seen it with cert-manager 1.13.3 as of now.

**Comment by llamerada-jp** [comment]
I checked my environment, cert-manager is 1.14.4, and the webhook is enabled. Does your environment set additional [options](https://cert-manager.io/docs/cli/webhook/) for webhooks?

I checked the cert-manager code, but could only find a webhook for the CertificateResuest custom resource and could not found logic for Certificate custom resource.
https://github.com/cert-manager/cert-manager/tree/master/internal/webhook/admission/certificaterequest

> The validating/mutating webhook portion of cert-manager is an optional component.

Does this mean it is a [external product](https://cert-manager.io/docs/configuration/acme/dns01/#webhook)?

**Comment by gozer** [comment]
> @gozer I agree with your change, and I am also experiencing this issue when installing the chart via ArgoCD. One small suggestion: instead of hardcoding, it would be nice if we can call it via values.yaml, allowing people to modify it based on their requirements.

Thanks! I didn't have time to dig down precisely where it's coming from so I can offer a reproductible test case. At least I am not alone.

And yes, making it a value makes a whole lot more sense. I'll fix the PR.

**Comment by toshipp** [comment]
@gozer 
Please check and answer @llamerada-jp's question. We can not approve this unless it is reasonable.

**Pull request closed without merging**
