### PR TITLE
add support for K8s metrics API as a source of PVC usage data

### PR DESCRIPTION
**Pull request by tropnikovvl**
Hello!

I was [previously interested](https://github.com/topolvm/pvc-autoresizer/issues/235) in the possibility of using a pvc-autoresizer without Prometheus and was given the answer that there had already been an attempt to do this.

I'm restarting [this](https://github.com/topolvm/pvc-autoresizer/pull/193) effort because I think it's important for users and I tried to take into account all your comments.

### CODE REVIEW

**Comment by llamerada-jp** [comment]
Commits merged before are mixed in this PR. Could you please clean this up by using rebase or otherwise?

**Comment by tropnikovvl** [comment]
> Commits merged before are mixed in this PR. Could you please clean this up by using rebase or otherwise?

Done

**Comment by ushitora-anqou** [comment]
Hi. Could you combine your commits into one? Currently, your PR has two separate commits (see [here](https://github.com/topolvm/pvc-autoresizer/pull/241/commits)).

Also, please only include a description of your changes in the commit message. It currently contains irrelevant messages.

**Comment by tropnikovvl** [comment]
I'm sorry, but I accidentally destroyed all my work with a rebase.

**Pull request closed without merging**
