### PR TITLE
adding annotations to the deployment

### PR DESCRIPTION
**Pull request by ekirmayer**
This will allow passing annotations at the deployment level. Allow supporting controllers which use the deployment annotations.

### CODE REVIEW

**Review by toshipp — DISMISSED** [review]

**Comment by ushitora-anqou** [comment]
@ekirmayer Could you update your code so that the CI can pass? It looks like you need to run `make generate` once. Thanks!

**Comment by ekirmayer** [comment]
@ushitora-anqou i see that there are two failing test on connectivity but i cant re-trigger the action. Is it something i need to fix?

**Comment by ushitora-anqou** [comment]
I don't think you need to fix anything. Actually, the e2e tests are kind of flaky. I'll retry them.

**Comment by toshipp** [comment]
This flakiness is consistently happened on CI. I'll try to solve it.

**Comment by toshipp** [comment]
@ekirmayer 
Hi, I fixed the flakiness, could you rebase on the main branch?

**Comment by toshipp** [comment]
Still failing... I'll dig into it more.

**Comment by toshipp** [comment]
I retried and CI passed. I suspect the flakiness may still exist, but we can proceed.

**Review by toshipp — APPROVED** [review]

**Review by ushitora-anqou — APPROVED** [review]

**Comment by ushitora-anqou** [comment]
Thank you for your contribution!

**Pull request merged**
