### PR TITLE
Add commands to update the version number.

### PR DESCRIPTION
**Pull request by cupnes**
Added commands to RELEASE.md to update the version number.
It prevents the omission of updating the version number.

Signed-off-by: Yuma Ogami <yuma-ogami@cybozu.co.jp>

### CODE REVIEW

**Review by toshipp — COMMENTED** [review]
Looks good, however, CI is failing due to the issue https://github.com/kubernetes-sigs/kubebuilder/issues/2311
Would you change the download URL for kubebuilder to the release assets?
https://github.com/kubernetes-sigs/kubebuilder/releases

**Review by toshipp — DISMISSED** [review]

**Comment by llamerada-jp** [comment]
The procedure of releasing Chart is operated after releasing main programs and images if I recall correctly. The procedure in this PR describing update both at the same time, is that correct?

**Comment by cupnes** [comment]
@llamerada-jp 
Indeed it is. The only command I'm going to add is for the chart, so I've put it in the "Release Helm Chart" section.

**Review by toshipp — APPROVED** [review]

**Review by llamerada-jp — APPROVED** [review]
LGTM

**Pull request merged**
