### PR TITLE
Add --no-annotation-check flag

### LINKED ISSUE #26: Update golang to 1.16.2
## What

Update golang to 1.16.2.

## How

- Add `go.sum` to repository.
- Update golang version in dockerfile, gihub actions or etc.
- Use `go install hoge@version` instead of `go get`.
- Remove `GO111MODULE=on`.
- Update source code using os & io package instead of `io/ioutil`.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

### LINKED ISSUE #27: Allow resizing without storage class annotation
We use GKE and it automatically provisions `standard` storage class:
https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#storageclasses

We already have many PVCs based on the default SC and we'd like to resize them with your magic software (thanks for that!). However, we are unable to manually annotate the SC because we are on the GitOps train. We are also unable to migrate data from existing PVCs onto ones based on a separately created (and properly annotated) SC.

Thus, the question is: is there a possibility to disable the requirement of having SC annotated?

### PR DESCRIPTION
**Pull request by ymmt2005**
close #26 
close #27

### CODE REVIEW

**Review by toshipp — APPROVED** [review]
LGTM

**Review by satoru-takeuchi — CHANGES_REQUESTED** [review]
Please also replace deplicated `io/ioutil` function with the corresponding functions in `os` and `io`.

**Comment by ymmt2005** [comment]
@satoru-takeuchi I can't see any.

```console
pvc-autoresizer$ g grep ioutil
(nothing)
```

**Comment by satoru-takeuchi** [comment]
Oops, I greped topolvm/topolvm, sorry.

**Review by satoru-takeuchi — APPROVED** [review]

**Pull request merged**
